
spring:
  jpa:
    properties:
      hibernate:
        format_sql : true
        highlight_sql : true
        use_sql_comments: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

